mcom02_flash_spi: Remove '0x' prefix for hexadecimals
There are two MCom-02 batches: 1447 with BootROM r0 and
1729 with BootROM r1.
BootROM r0 has an issue rf#1354: set/dump UART commands
doesn't interpret 0x prefix for hexadecimals.

After commit 73043b "mcom02_flash_spi: Add Atmel flash support"
we started adding 0x prefix which broke compatibility of
tools with BootROM r0.
Flashing BootROM r0 chips fails with message:

  Error: Device does not respond on set 0x3809404c 0x681001

Issue: #MCOM02SW-1795
Change-Id: Iec88870834a573a450810f028f5d7fccd47670f3